// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cli_g.proto
#ifndef GRPC_cli_5fg_2eproto__INCLUDED
#define GRPC_cli_5fg_2eproto__INCLUDED

#include "cli_g.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace serv_g {

class ServG final {
 public:
  static constexpr char const* service_full_name() {
    return "serv_g.ServG";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::serv_g::TranslatedString* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::serv_g::TranslatedString>> AsyncGetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::serv_g::TranslatedString>>(AsyncGetTranslateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::serv_g::TranslatedString>> PrepareAsyncGetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::serv_g::TranslatedString>>(PrepareAsyncGetTranslateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr* request, ::serv_g::TranslatedString* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr* request, ::serv_g::TranslatedString* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::serv_g::TranslatedString>* AsyncGetTranslateRaw(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::serv_g::TranslatedString>* PrepareAsyncGetTranslateRaw(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::serv_g::TranslatedString* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::serv_g::TranslatedString>> AsyncGetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::serv_g::TranslatedString>>(AsyncGetTranslateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::serv_g::TranslatedString>> PrepareAsyncGetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::serv_g::TranslatedString>>(PrepareAsyncGetTranslateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr* request, ::serv_g::TranslatedString* response, std::function<void(::grpc::Status)>) override;
      void GetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr* request, ::serv_g::TranslatedString* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::serv_g::TranslatedString>* AsyncGetTranslateRaw(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::serv_g::TranslatedString>* PrepareAsyncGetTranslateRaw(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetTranslate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetTranslate(::grpc::ServerContext* context, const ::serv_g::TargetStr* request, ::serv_g::TranslatedString* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetTranslate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetTranslate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetTranslate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTranslate(::grpc::ServerContext* /*context*/, const ::serv_g::TargetStr* /*request*/, ::serv_g::TranslatedString* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTranslate(::grpc::ServerContext* context, ::serv_g::TargetStr* request, ::grpc::ServerAsyncResponseWriter< ::serv_g::TranslatedString>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetTranslate<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetTranslate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetTranslate() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::serv_g::TargetStr, ::serv_g::TranslatedString>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::serv_g::TargetStr* request, ::serv_g::TranslatedString* response) { return this->GetTranslate(context, request, response); }));}
    void SetMessageAllocatorFor_GetTranslate(
        ::grpc::MessageAllocator< ::serv_g::TargetStr, ::serv_g::TranslatedString>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::serv_g::TargetStr, ::serv_g::TranslatedString>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetTranslate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTranslate(::grpc::ServerContext* /*context*/, const ::serv_g::TargetStr* /*request*/, ::serv_g::TranslatedString* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTranslate(
      ::grpc::CallbackServerContext* /*context*/, const ::serv_g::TargetStr* /*request*/, ::serv_g::TranslatedString* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetTranslate<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetTranslate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetTranslate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetTranslate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTranslate(::grpc::ServerContext* /*context*/, const ::serv_g::TargetStr* /*request*/, ::serv_g::TranslatedString* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetTranslate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetTranslate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetTranslate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTranslate(::grpc::ServerContext* /*context*/, const ::serv_g::TargetStr* /*request*/, ::serv_g::TranslatedString* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTranslate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetTranslate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetTranslate() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetTranslate(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetTranslate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTranslate(::grpc::ServerContext* /*context*/, const ::serv_g::TargetStr* /*request*/, ::serv_g::TranslatedString* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTranslate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetTranslate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetTranslate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::serv_g::TargetStr, ::serv_g::TranslatedString>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::serv_g::TargetStr, ::serv_g::TranslatedString>* streamer) {
                       return this->StreamedGetTranslate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetTranslate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetTranslate(::grpc::ServerContext* /*context*/, const ::serv_g::TargetStr* /*request*/, ::serv_g::TranslatedString* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetTranslate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::serv_g::TargetStr,::serv_g::TranslatedString>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetTranslate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetTranslate<Service > StreamedService;
};

}  // namespace serv_g


#endif  // GRPC_cli_5fg_2eproto__INCLUDED
