// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cli_g.proto

#include "cli_g.pb.h"
#include "cli_g.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace serv_g {

static const char* ServG_method_names[] = {
  "/serv_g.ServG/GetTranslate",
};

std::unique_ptr< ServG::Stub> ServG::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServG::Stub> stub(new ServG::Stub(channel, options));
  return stub;
}

ServG::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetTranslate_(ServG_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServG::Stub::GetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::serv_g::TranslatedString* response) {
  return ::grpc::internal::BlockingUnaryCall< ::serv_g::TargetStr, ::serv_g::TranslatedString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTranslate_, context, request, response);
}

void ServG::Stub::async::GetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr* request, ::serv_g::TranslatedString* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::serv_g::TargetStr, ::serv_g::TranslatedString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTranslate_, context, request, response, std::move(f));
}

void ServG::Stub::async::GetTranslate(::grpc::ClientContext* context, const ::serv_g::TargetStr* request, ::serv_g::TranslatedString* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTranslate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::serv_g::TranslatedString>* ServG::Stub::PrepareAsyncGetTranslateRaw(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::serv_g::TranslatedString, ::serv_g::TargetStr, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTranslate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::serv_g::TranslatedString>* ServG::Stub::AsyncGetTranslateRaw(::grpc::ClientContext* context, const ::serv_g::TargetStr& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTranslateRaw(context, request, cq);
  result->StartCall();
  return result;
}

ServG::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServG_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServG::Service, ::serv_g::TargetStr, ::serv_g::TranslatedString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServG::Service* service,
             ::grpc::ServerContext* ctx,
             const ::serv_g::TargetStr* req,
             ::serv_g::TranslatedString* resp) {
               return service->GetTranslate(ctx, req, resp);
             }, this)));
}

ServG::Service::~Service() {
}

::grpc::Status ServG::Service::GetTranslate(::grpc::ServerContext* context, const ::serv_g::TargetStr* request, ::serv_g::TranslatedString* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace serv_g

