# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_serv import serv_g_pb2 as grpc__serv_dot_serv__g__pb2


class ServGStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTranslate = channel.unary_unary(
                '/serv_g.ServG/GetTranslate',
                request_serializer=grpc__serv_dot_serv__g__pb2.TargetStr.SerializeToString,
                response_deserializer=grpc__serv_dot_serv__g__pb2.TranslatedString.FromString,
                )


class ServGServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTranslate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServGServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTranslate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranslate,
                    request_deserializer=grpc__serv_dot_serv__g__pb2.TargetStr.FromString,
                    response_serializer=grpc__serv_dot_serv__g__pb2.TranslatedString.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serv_g.ServG', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServG(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTranslate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serv_g.ServG/GetTranslate',
            grpc__serv_dot_serv__g__pb2.TargetStr.SerializeToString,
            grpc__serv_dot_serv__g__pb2.TranslatedString.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
