# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_serv/serv_g.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16grpc_serv/serv_g.proto\x12\x06serv_g\"\'\n\tTargetStr\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x65xit\x18\x05 \x01(\x08\"g\n\x10TranslatedString\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x17\n\ntranslated\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04time\x18\x04 \x01(\rH\x01\x88\x01\x01\x42\r\n\x0b_translatedB\x07\n\x05_time2F\n\x05ServG\x12=\n\x0cGetTranslate\x12\x11.serv_g.TargetStr\x1a\x18.serv_g.TranslatedString\"\x00\x62\x06proto3')



_TARGETSTR = DESCRIPTOR.message_types_by_name['TargetStr']
_TRANSLATEDSTRING = DESCRIPTOR.message_types_by_name['TranslatedString']
TargetStr = _reflection.GeneratedProtocolMessageType('TargetStr', (_message.Message,), {
  'DESCRIPTOR' : _TARGETSTR,
  '__module__' : 'grpc_serv.serv_g_pb2'
  # @@protoc_insertion_point(class_scope:serv_g.TargetStr)
  })
_sym_db.RegisterMessage(TargetStr)

TranslatedString = _reflection.GeneratedProtocolMessageType('TranslatedString', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATEDSTRING,
  '__module__' : 'grpc_serv.serv_g_pb2'
  # @@protoc_insertion_point(class_scope:serv_g.TranslatedString)
  })
_sym_db.RegisterMessage(TranslatedString)

_SERVG = DESCRIPTOR.services_by_name['ServG']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TARGETSTR._serialized_start=34
  _TARGETSTR._serialized_end=73
  _TRANSLATEDSTRING._serialized_start=75
  _TRANSLATEDSTRING._serialized_end=178
  _SERVG._serialized_start=180
  _SERVG._serialized_end=250
# @@protoc_insertion_point(module_scope)
